import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Search, UserRound, X } from "lucide-react";
import { useState } from "react";
import { api, json } from "../api/client";
import { PageHeader } from "../components/PageHeader";
import { EmptyState } from "../components/EmptyState";

interface Customer { id:string; first_name:string; last_name:string; email:string; phone:string|null; booking_count:number; latest_booking_at:string|null; total_paid_minor:number; ghl_contact_id:string|null }
interface Detail extends Customer { notes:{id:string;body:string;author_name:string|null;created_at:string}[]; custom_fields:Record<string,unknown>; bookings:{id:string;public_reference:string;calendar_name:string;start_at:string;units:number;status:string;total_minor:number}[] }
const money=(minor:number)=>new Intl.NumberFormat(undefined,{style:"currency",currency:"USD"}).format(minor/100);

function CustomerDrawer({ customerId, onClose }:{ customerId:string; onClose:()=>void }) {
  const client=useQueryClient(); const detail=useQuery({queryKey:["customer",customerId],queryFn:()=>api<Detail>(`/customers/${customerId}`)}); const [body,setBody]=useState("");
  const addNote=useMutation({mutationFn:()=>api(`/customers/${customerId}/notes`,json("POST",{body})),onSuccess:()=>{setBody("");void client.invalidateQueries({queryKey:["customer",customerId]});}});
  return <><button className="drawer-overlay" onClick={onClose} aria-label="Close customer"/><aside className="drawer" aria-label="Customer details">{detail.isLoading||!detail.data?<div className="loading">Loading customer…</div>:<><div className="drawer-header"><div><h2>{detail.data.first_name} {detail.data.last_name}</h2><p>{detail.data.email}</p></div><button className="icon-button" onClick={onClose}><X size={18}/></button></div><div className="detail-section"><h3>Customer profile</h3><dl className="detail-list"><dt>Phone</dt><dd>{detail.data.phone||"—"}</dd><dt>Bookings</dt><dd>{detail.data.booking_count}</dd><dt>Total paid</dt><dd>{money(detail.data.total_paid_minor)}</dd><dt>GHL contact</dt><dd>{detail.data.ghl_contact_id||"Not projected"}</dd></dl></div><div className="detail-section"><h3>Booking history</h3>{detail.data.bookings.length?detail.data.bookings.map(item=><div className="note" key={item.id}><strong>{item.calendar_name}</strong><p>{item.public_reference} · {new Date(item.start_at).toLocaleString()} · {item.units} unit{item.units===1?"":"s"}</p><span className={`badge ${item.status==="confirmed"?"success":item.status==="cancelled"?"danger":""}`}>{item.status.replaceAll("_"," ")}</span></div>):<p className="muted-note">No booking history.</p>}</div><div className="detail-section"><h3>Internal notes</h3>{detail.data.notes.map(note=><div className="note" key={note.id}><p>{note.body}</p><small>{note.author_name||"Team member"} · {new Date(note.created_at).toLocaleString()}</small></div>)}<form className="note-form" onSubmit={e=>{e.preventDefault();if(body.trim())addNote.mutate();}}><textarea className="control" rows={3} placeholder="Add a customer note…" value={body} onChange={e=>setBody(e.target.value)}/><button className="button small" disabled={!body.trim()||addNote.isPending}>Add note</button></form></div></>}</aside></>;
}

export function CustomersPage(){const [search,setSearch]=useState("");const [selected,setSelected]=useState<string|null>(null);const customers=useQuery({queryKey:["customers",search],queryFn:()=>api<Customer[]>(`/customers?${new URLSearchParams(search?{search}: {})}`)});return <div className="page"><PageHeader title="Customers" description="Passport-owned customer records, booking history, lifetime value, waivers, and notes."/><div className="toolbar" style={{marginBottom:16}}><label className="search-field"><Search size={16}/><input placeholder="Search name, email, or phone" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="card table-card">{customers.isLoading?<div className="loading">Loading customers…</div>:!customers.data?.length?<EmptyState title="No customers found" copy="Customers are created automatically when bookings are made."/>:<table className="data-table"><thead><tr><th>Customer</th><th>Contact</th><th>Bookings</th><th>Lifetime value</th><th>Last booking</th><th>Passport / GHL</th></tr></thead><tbody>{customers.data.map(customer=><tr key={customer.id} onClick={()=>setSelected(customer.id)} style={{cursor:"pointer"}}><td><div className="cell-title"><strong>{customer.first_name} {customer.last_name}</strong><span>{customer.email}</span></div></td><td>{customer.phone||"—"}</td><td>{customer.booking_count}</td><td>{money(customer.total_paid_minor)}</td><td>{customer.latest_booking_at?new Date(customer.latest_booking_at).toLocaleDateString():"—"}</td><td><span className={`badge ${customer.ghl_contact_id?"success":""}`}><UserRound size={12}/>{customer.ghl_contact_id?"Projected":"Passport only"}</span></td></tr>)}</tbody></table>}</div>{selected&&<CustomerDrawer customerId={selected} onClose={()=>setSelected(null)}/>}</div>}
